### ISSUE TITLE
Not asking for width/height

### ISSUE THREAD

**Issue by intelligence** [pyramidium/generator-bannertime#1]
First and foremost, great initiative, seems like an amazing generator!

I noticed that the setup doesn't ask for width/height as described in the usage instructions. Is this expected behaviour? It sets up 300x250 for me automatically.

Thanks!

**Comment by pyramidium** [comment]
Thanks and I'm happy to hear that you like it!

I recently removed the setup prompts to set a width and height for the demonstration banner and I am yet to update the documentation. However I intend to create a sub generator at some point which will provide a method of creating new banners and adding the banner to the preview page.

For now you can change the width and height of the demonstration banner by changing the width and height variables in _banner.scss and the ad.size meta tag in the banner's index.html.

Hope this helps.

**Comment by intelligence** [comment]
Yeah, that makes sense, excellent. Was just curious why I didn't get prompted.
Also bit curious on how to increase productivity when it comes to the same creative but for different sizes. At this point I usually just duplicate the banner I create first and then resize/move content accordingly. Would be nice to figure some sort of templating that is true for multiple sizes or even campaign (if you have a client that always use a certain color, font or logo placement for example).

The landscape for HTML5 banners is still pretty vague it seems, but this tool will help a lot, thanks again!

**Comment by joemidi** [comment]
So we've discussed this (over a beer, yay!), and we're thinking that it might be a good idea for the prompt to ask if you're making just a single banner or a collection/campaign/set/, if you say single, it will ask you for width and height like normal, if you say collection maybe just make a 300x250 by default.

Then if you have chosen collection, include a sub-generator for creating a new size of an pre-existing size, so if you want to make a 300x600 from a 300x250 or you have a 728x90 and you want to make a 970x250?

Something like that perhaps?

**Comment by pyramidium** [comment]
For the time being, I have just been creating a master banner at 300x250 and then manually copying the folder and updating the two files I mentioned above. I then manually add the new banner path to the base index file in `src/index.html` to add it to the preview page.

I intend to create a sub generator to handle this process. For example, there could be an option to create a completely new banner using `yo bannertime:new` or an option to copy the existing banner and change the dimensions of a master banner using `yo bannertime:copy`.

**Comment by joemidi** [comment]
Does that ask you more questions? or would you be able to write `yo bannertime:copy 300x250 300x600`

**Comment by pyramidium** [comment]
I think that the best route would be to prompt the user with questions per banner. It would work in a similar way to the main generator except the user will be prompted with questions related to the sub-generator. For example, `yo bannertime:new` would then prompt the user with `Set the width of the banner` and `Set the height of the banner` and maybe also the ad platform as there have been a few occasions where the same client has required multiple platforms according to their publisher's needs.

**Comment by intelligence** [comment]
Good thoughts!

What struck me as something useful would be to have top level declaration that trickles down into the sub banners. For example for deciding primary color, secondary color, logo placement and what not. What do you think?

**Comment by pyramidium** [comment]
Good suggestion. However, Due to the nature of HTML5 banners, I don't think that it is worth adding the ability to define a primary colour, a secondary colour or the logo placement as banners differ from one another. Some banners may include the logo as part of an image, others as a transparent png and some may not even have a logo or colours for that matter.

**Comment by intelligence** [comment]
Fair enough. I'd need it for a current client, but probably way too specific for a general use case!
