### ISSUE TITLE
Not using images, what to do. 

### ISSUE THREAD

**Issue by rgfx** [pyramidium/generator-bannertime#102]
I am using an inline SVG, when I comment out the image array the banner breaks. I tried removing everything that references image preloading and still having issues. Surely I can't be the only one that doesn't use images. 

    this.images = [
    //'images/logo.png'
    ];

Please advise.

**Comment by joemidi** [comment]
Hmm,

This should work:
```js
  // Image array for preloading
  // this.images = [
  //   'images/logo.png'
  // ];

  // var _this = this;
  // this.preloadImages(this.images, function () {
    this.createElements();
    this.setup();
    this.hidePreloader();
    this.animate();
    this.bindEvents();
  // });
```

**Comment by rgfx** [comment]
That works

 I had to uncomment var _this = this;

Thanks.
