### ISSUE TITLE
Watch Task Not Working

### ISSUE THREAD

**Issue by douglaswelcome** [pyramidium/generator-bannertime#104]
Hey folks,

Really getting into this project appreciate the work.

One struggle: for some reason, the watch task either isn't watching the right folders for me or not running everytime I make a save. For now, I have to rerun the entire gulp task to see the updates.

I just started using bannertime and haven't done anything wild as far as file structure. SImply created a campaign folder and then ran bannertime from in there. The only thing I did do was not install bannertime globally, but only in the folder I am working in so I can make slight changes to more quickly set up projects

Thanks

Douglas Welcome

**Comment by pyramidium** [comment]
Hi Douglas,

Good to hear you are getting into Bannertime.

It would help us a bit to get to the bottom of your issue by providing a bit more information about your setup. Which operating system are you running? Which version of node/npm? Have you altered the file/folder structure?

**Comment by douglaswelcome** [comment]
Thanks for responding. I am pretty new to front-end stuff in general, so any help is appreciated.

OS: macOS 10.12.6
node version: v6.11.3
npm version: 3.10.10

Here's a screenshot of my file structure. I haven't manually moved anything around and it doesn't look different to the one [here](https://bannertime.github.io/documentation/file-structure/#file-structure)
<img width="261" alt="screen shot 2017-10-24 at 1 01 11 pm" src="https://user-images.githubusercontent.com/9753618/31965216-7567db9e-b8bb-11e7-9c42-11c0fc2ddb53.png">

Lemme know if there is anything else I can provide

**Comment by pyramidium** [comment]
I just installed node v6.11.3 and tested and the watch task is firing on save as expected. When you run `npm start` do you see `[00:00:00] Starting 'watch'...` in terminal?

**Comment by douglaswelcome** [comment]
yeah, here's a screenshot of my terminal from npm start:

<img width="740" alt="screen shot 2017-10-24 at 1 24 51 pm" src="https://user-images.githubusercontent.com/9753618/31966233-dea7b27a-b8be-11e7-88ea-b874adbfdf25.png">

**Comment by pyramidium** [comment]
Try updating the path in `./gulpfile.js/config.js` to the respective file you are trying to watch.

**Comment by douglaswelcome** [comment]
Ok, I figured it out. I had to change all the watch functions in the watch.js file from `watch` to `gulp.watch`

Thanks for all your help and build such a great tool!

**Comment by pyramidium** [comment]
Ah ok, happy to hear you figured it out. I'm going to update this in the next release. Happy coding!
