### ISSUE TITLE
feat: generate spritesheet from images in sprites folder

### ISSUE THREAD

**Issue by pyramidium** [pyramidium/generator-bannertime#12]
This feature was requested on the greensock forums.

http://greensock.com/forums/topic/12734-stop-its-duncan-bannertime/#entry54799

**Comment by joemidi** [comment]
If using [gulp.spritesmith](https://github.com/twolfson/gulp.spritesmith) Would you need to put in a `sprite: true` flag when you create the `smartObject` to let the `backgroundPosition` get picked up by the outputted CSS ?

**Comment by pyramidium** [comment]
Yeah I think that would work. Creating the spritesheet is fairly trivial. The thing that requires a bit of forethought is how each sprite is baked into a smart object.

**Comment by joemidi** [comment]
Yea, thats what I was thinking.

**Comment by pyramidium** [comment]
Going to close this one for now. Maybe we can look into this in a future release.
