### ISSUE TITLE
CSS backgroundSize: auto 100% becomes to background-size: 50% 100%

### ISSUE THREAD

**Issue by nrgnrg** [pyramidium/generator-bannertime#125]
When using smart objects adding backgroundSize: auto 100% gets compiled to background-size: 50% 100% in CSS which behaves very differently.

**Comment by joemidi** [comment]
Hi, the `smartObject` set methods are just a shorthand for [GSAP](https://github.com/greensock/GreenSock-JS) TweenMax, and it prefers numbers over strings.
I would use vanilla JS to set it i.e.: `this.mySmartObject.style.backgroundSize`
