### ISSUE TITLE
upgrade to gulp 4.0

### ISSUE THREAD

**Issue by adam-hite** [pyramidium/generator-bannertime#126]
I'm on the most recent version of node (12.4) which is not compatible with Gulp 3.9.1, so I'm getting errors from _npm install_ and _npm start_.

From what I've researched, you either have to upgrade Gulp or downgrade your version of node. I can downgrade node for now, but it seems like Gulp needs to be upgraded at some point.

In the meantime, could you add an "engines" field to the **package.json** so developers know what version of node will definitely work with bannertime?

The error I'm getting is "ReferenceError: primordials is not defined"

**Comment by pyramidium** [comment]
Hi Adam, we were planning to remove Gulp altogether in a future release and replace it with our own CLI. For the time being using the LTS release of node (10.16.0) is recommended.

I'll add engines to the `package.json` now 👍

**Comment by pyramidium** [comment]
https://github.com/bannertime/generator-bannertime/pull/127

**Comment by adam-hite** [comment]
thanks!
