### ISSUE TITLE
feat: spritesheets

### ISSUE THREAD

**Issue by barrypollinate** [pyramidium/generator-bannertime#13]
Spritesheet generation would be a great feature to add. Perhaps gulp.spritesmith?

**Comment by pyramidium** [comment]
How odd I created an issue at exactly the same time as you #12. Great idea. I have implemented this in the past using gulp-spritesmith so it should be pretty straight-forward.

**Comment by joemidi** [comment]
Duplicate of #12

**Comment by barrypollinate** [comment]
I got the notification that you created this literally at the same moment I posted.. ha!

**Comment by pyramidium** [comment]
:+1:
