### ISSUE TITLE
docs: Add a bit more in depth walkthrough to the initial installation and first run

### ISSUE THREAD

**Issue by dipscom** [pyramidium/generator-bannertime#27]
Hey,

Giving the generator the first spin but find that it could benefit with a little bit more in depth "first steps" here. I am happy to write up and contribute. 

Like, I had terminal throw a ton of errors when installing for the first time, not sure if anything is broken or not. Also, I didn't have the Sass gem installed so, it also threw an error.

It will be fine for me to go over those errors and install whatever is needed but I think that we need to make it as smooth of a ride as possible. Not everyone is comfortable with the Terminal.

**Comment by pyramidium** [comment]
I agree, the installation steps are not great and they could do with a bit of work. If you feel you could help out and write them up a bit better, contributions are welcome. Feel free to fork the repo and submit a pull request.

**Comment by dipscom** [comment]
Aye, I will sink my teeth on this, then.

**Comment by pyramidium** [comment]
Going to go ahead and close this because I have updated the docs here: http://pyramidium.github.io/generator-bannertime
