### ISSUE TITLE
feat: create new prompt option for AdWords

### ISSUE THREAD

**Issue by joemidi** [pyramidium/generator-bannertime#59]

**Comment by cmnstmntmn** [comment]
any ideea about a workaround for google adword? they get uploaded, but soon after they are rejected for this reason **Malicious or unwanted software**

i also replaced these lines

``` js
'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenLite.min.js',
'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TimelineLite.min.js',
'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/CSSPlugin.min.js',
'https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/easing/EasePack.min.js'
```

with

``` js
 'https://s0.2mdn.net/ads/studio/cached_libs/tweenlite_1.19.0_422f021fad4c20f20cf3640a06ac39e9_min.js',
 'https://s0.2mdn.net/ads/studio/cached_libs/timelinelite_1.19.0_13e3bd0e510d63fd5e5ef9bf9dac7017_min.js',
 'https://s0.2mdn.net/ads/studio/cached_libs/cssplugin_1.19.0_cfbff7d208ccfdbe176b9855af1eb1fa_min.js',
 'https://s0.2mdn.net/ads/studio/cached_libs/easepack_1.19.0_be87087c08fcec83e2b64c70571fe91f_min.js'
```

taken from [here](https://support.google.com/richmedia/answer/6307288?hl=en)

i tested them here https://h5validator.appspot.com/adwords and everything is 100% ok.
have no ideea what to do.

here's one of the banners.

[adg-160x600.zip](https://github.com/pyramidium/generator-bannertime/files/506996/adg-160x600.zip)

**Comment by joemidi** [comment]
Ah yea, this is a known issue with AdWords, you can't use anything other than the ones they specifically mention on this [policy page](https://support.google.com/adwordspolicy/answer/176108?hl=en-GB).

They have a much stricter policy than their sibling Google powered ad platforms.

``` js
// Google-hosted Greensock
'https://s0.2mdn.net/ads/studio/cached_libs/tweenlite_1.18.0_56fa823cfbbef1c2f4d4346f0f0e6c3c_min.js',
'https://s0.2mdn.net/ads/studio/cached_libs/tweenmax_1.18.0_499ba64a23378545748ff12d372e59e9_min.js',
'https://s0.2mdn.net/ads/studio/cached_libs/cssplugin_1.18.0_71489205621d46cbe88348eeb8fe493f_min.js',
'https://s0.2mdn.net/ads/studio/cached_libs/easepack_1.18.0_ed5816e732515f56d96a67f6a2a15ccb_min.js',
```

Realistically you only need the TweenMax lib as it contains all the others:

``` js
'https://s0.2mdn.net/ads/studio/cached_libs/tweenmax_1.18.0_499ba64a23378545748ff12d372e59e9_min.js',
```

**Comment by joemidi** [comment]
Also from what you can see, you need to also replace your clickTag Event.

> HTML5 ads that are not created in Google Web Designer are, by default, clickable on the entire area of the ad. If you wish to limit the clickable area to specific elements, then you will need to include the exitapi.js script.

You can either remove the bind event event entirely and let the AdWords platform take over.

Or add the ExitApi

``` html
<script type="text/javascript" src="https://tpc.googlesyndication.com/pagead/
gadgets/html5/api/exitapi.js"> </script>
```

Which would change the Bind Event to:

``` js
Banner.prototype.bindEvents=function(){
  this.banner.addEventListener('click', function() {
    ExitApi.exit());
  });
};
```

**Comment by cmnstmntmn** [comment]
thank you :)

since removing was easier, i removed the binding event :)
now waiting to see what happen

**Comment by cmnstmntmn** [comment]
they've been approved. thank you!
