### ISSUE TITLE
feat: support for mraid

### ISSUE THREAD

**Issue by intelligence** [pyramidium/generator-bannertime#61]
Hey!

Adform (amongst others) use MRAID for mobile banners. Would be cool to see it implemented at some point!

http://support.adform.com/documentation/build-mobile-mraid-banners/create-a-mobile-html5-banner/using-mraid/
http://support.adform.com/documentation/build-mobile-mraid-banners/general-specifications/

**Comment by joemidi** [comment]
Hey @intelligence, do any example banners that you could share?

I've never needed to include MRAID compatibility so I'm not quite sure how to implement this.

Is it really as simple as adding a question?

```
? Do you need MRAID compatibility? (yes/no)
```

And that just drops into the HTML index:

```
    <script src="mraid.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="HandheldFriendly" content="True" />
```

**Comment by pyramidium** [comment]
Closing this as MRAID is fairly simple to implement when required and can be copied using the copy sub-generator
